SELECTED_BASE_TEMPLATE_NAME: 'req-reviewer-instruct-2'
MAIN_DATA_FOLDER: './src/data'
INCOSE_GUIDE_FILEPATH: './src/data/incose_gtwr.pdf'
INCOSE_SECTIONS_REGEX_PAT: r'([1-9]\.([0-9]+\.)?[0-9]?)[\s]+R\d'
REPLACE_TOKENS:
  - 'INCOSE-TP-2010-006-04| VERS/REV:4  |  1 July 2023'
  - '{'
  - '}'
REPLACE_WITH: ' '
LLM_MODEL_NAME: 'gpt-4o-mini'
DATASET_REQ_COLNAME: 'Requirement'
MAX_NUM_ITER: 1